### ISSUE TITLE
Phone not going into deep sleep with the module activated

### ISSUE THREAD

**Issue by Dinara293** [skyguy126/Xposed-SoundCloudDownloader#18]
My phone absolutely refuses to go into deep sleep with the module activated. The module works perfectly fine, but without the phone going to deep sleep, the battery is a goner. I'm on the latest march update. Please do look into this, thank you.

**Comment by skyguy126** [comment]
I'm not 100% sure what this means, or how deep sleep works but I can only think of one reason why this module might affect deep sleep and that's because I'm having to store the current activity in a static variable which probably doesn't get cleared when the app closes. I can see if theres a way around that.

**Comment by skyguy126** [comment]
please re-open this issue if its still an issue.
